@startuml
actor Klient
actor SystemPracowniczy

' Bazy danych
database "Baza Danych Kont" as BazaKont
database "Baza Danych Magazynu" as BazaMagazyn


' Klient interakcje
Klient --> (Logowanie)
(Logowanie) --> BazaKont : Odczyt danych logowania

Klient --> (Stwórz Konto)
(Stwórz Konto) --> BazaKont : Zapis nowego konta

Klient --> (Przeglądaj Asortyment)
(Przeglądaj Asortyment) --> BazaMagazyn : Odczyt danych produktów

Klient --> (Asortyment do przechowania)
(Asortyment do przechowania) --> BazaMagazyn : Sprawdzenie dostępności miejsca do przechowywania
(Asortyment do przechowania) --> "Baza Danych Magazynu" : Zapis zamówienia na przestrzeń do przechowywania

Klient --> (Pokaż Sumę twoich produktów w magazynie)
(Pokaż Sumę twoich produktów w magazynie) --> "Baza Danych Magazynu" : Odczyt ceny zamówienia

' System Pracowniczy interakcje
SystemPracowniczy --> (Logowanie)
(Logowanie) --> BazaKont : Odczyt danych logowania

SystemPracowniczy --> (Przeglądaj Asortyment)
(Przeglądaj Asortyment) --> BazaMagazyn : Odczyt danych produktów

SystemPracowniczy --> (Dodaj Asortyment)
(Dodaj Asortyment) --> BazaMagazyn : Dodanie nowego produktu

SystemPracowniczy --> (Usuń Asortyment)
(Usuń Asortyment) --> BazaMagazyn : Usunięcie produktu

SystemPracowniczy --> (Zarządzaj Kontami Klientów)
(Zarządzaj Kontami Klientów) --> BazaKont : Modyfikacja/usunięcie kont klientów
@enduml
